export function generateQuotationPDF(quote: any, items: any[], company: any, client: any): string {
  const formatMoney = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: company.currency || "USD" }).format(n);
  const formatDate = (d: string) => d ? new Date(d).toLocaleDateString() : "—";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Quotation ${quote.number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', Arial, sans-serif; color: #1a1a1a; padding: 40px; }
    .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .company-info h1 { font-size: 24px; color: #0A2540; margin-bottom: 8px; }
    .company-info p { font-size: 14px; color: #666; }
    .quote-info { text-align: right; }
    .quote-info h2 { font-size: 32px; color: #0A2540; margin-bottom: 8px; }
    .quote-info p { font-size: 14px; color: #666; }
    .section { margin-bottom: 30px; }
    .section h3 { font-size: 14px; text-transform: uppercase; color: #666; margin-bottom: 10px; letter-spacing: 0.5px; }
    .bill-to { background: #f8f9fa; padding: 16px; border-radius: 6px; }
    .bill-to p { font-size: 14px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #0A2540; color: white; padding: 12px; text-align: left; font-size: 13px; font-weight: 600; }
    td { padding: 12px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    td.right, th.right { text-align: right; }
    .totals { margin-left: auto; width: 300px; margin-top: 20px; }
    .totals-row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 14px; }
    .totals-row.total { border-top: 2px solid #0A2540; padding-top: 12px; margin-top: 8px; font-size: 18px; font-weight: bold; color: #0A2540; }
    .notes { margin-top: 40px; padding: 16px; background: #f8f9fa; border-radius: 6px; font-size: 14px; line-height: 1.6; }
    .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #999; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-info">
      <h1>${company.name || "Your Company"}</h1>
      <p>Quotation</p>
    </div>
    <div class="quote-info">
      <h2>${quote.number}</h2>
      <p>Issued: ${formatDate(quote.issue_date)}</p>
      <p>Expires: ${formatDate(quote.expiry_date)}</p>
      <p>Status: ${quote.status.toUpperCase()}</p>
    </div>
  </div>

  <div class="section">
    <h3>Bill To</h3>
    <div class="bill-to">
      <p><strong>${client?.name || "Client"}</strong></p>
      ${client?.email ? `<p>${client.email}</p>` : ""}
      ${client?.address ? `<p>${client.address}</p>` : ""}
    </div>
  </div>

  <div class="section">
    <h3>Items</h3>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th class="right">Qty</th>
          <th class="right">Unit Price</th>
          <th class="right">Tax</th>
          <th class="right">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${items.map((item: any) => `
          <tr>
            <td>${item.description}</td>
            <td class="right">${Number(item.quantity)}</td>
            <td class="right">${formatMoney(Number(item.unit_price))}</td>
            <td class="right">${Number(item.tax_rate)}%</td>
            <td class="right">${formatMoney(Number(item.amount))}</td>
          </tr>
        `).join("")}
      </tbody>
    </table>

    <div class="totals">
      <div class="totals-row">
        <span>Subtotal</span>
        <span>${formatMoney(Number(quote.subtotal))}</span>
      </div>
      <div class="totals-row">
        <span>Tax</span>
        <span>${formatMoney(Number(quote.tax_total))}</span>
      </div>
      <div class="totals-row total">
        <span>Total</span>
        <span>${formatMoney(Number(quote.total))}</span>
      </div>
    </div>
  </div>

  ${quote.notes ? `
    <div class="notes">
      <h3>Notes</h3>
      <p>${quote.notes}</p>
    </div>
  ` : ""}

  <div class="footer">
    <p>Generated by Quoinv — quoinv.com</p>
  </div>
</body>
</html>
  `;
}

export function generateInvoicePDF(inv: any, items: any[], company: any, client: any): string {
  const formatMoney = (n: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: company.currency || "USD" }).format(n);
  const formatDate = (d: string) => d ? new Date(d).toLocaleDateString() : "—";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Invoice ${inv.number}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', Arial, sans-serif; color: #1a1a1a; padding: 40px; }
    .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
    .company-info h1 { font-size: 24px; color: #0A2540; margin-bottom: 8px; }
    .company-info p { font-size: 14px; color: #666; }
    .invoice-info { text-align: right; }
    .invoice-info h2 { font-size: 32px; color: #0A2540; margin-bottom: 8px; }
    .invoice-info p { font-size: 14px; color: #666; }
    .section { margin-bottom: 30px; }
    .section h3 { font-size: 14px; text-transform: uppercase; color: #666; margin-bottom: 10px; letter-spacing: 0.5px; }
    .bill-to { background: #f8f9fa; padding: 16px; border-radius: 6px; }
    .bill-to p { font-size: 14px; line-height: 1.6; }
    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
    th { background: #0A2540; color: white; padding: 12px; text-align: left; font-size: 13px; font-weight: 600; }
    td { padding: 12px; border-bottom: 1px solid #e5e7eb; font-size: 14px; }
    td.right, th.right { text-align: right; }
    .totals { margin-left: auto; width: 300px; margin-top: 20px; }
    .totals-row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 14px; }
    .totals-row.total { border-top: 2px solid #0A2540; padding-top: 12px; margin-top: 8px; font-size: 18px; font-weight: bold; color: #0A2540; }
    .payment-info { margin-top: 20px; padding: 12px; background: #f0fdf4; border-left: 3px solid #22c55e; font-size: 14px; }
    .payment-info.overdue { background: #fef2f2; border-left-color: #ef4444; }
    .notes { margin-top: 40px; padding: 16px; background: #f8f9fa; border-radius: 6px; font-size: 14px; line-height: 1.6; }
    .footer { margin-top: 60px; text-align: center; font-size: 12px; color: #999; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-info">
      <h1>${company.name || "Your Company"}</h1>
      <p>Invoice</p>
    </div>
    <div class="invoice-info">
      <h2>${inv.number}</h2>
      <p>Issued: ${formatDate(inv.issue_date)}</p>
      <p>Due: ${formatDate(inv.due_date)}</p>
      <p>Status: ${inv.status.toUpperCase()}</p>
    </div>
  </div>

  <div class="section">
    <h3>Bill To</h3>
    <div class="bill-to">
      <p><strong>${client?.name || "Client"}</strong></p>
      ${client?.email ? `<p>${client.email}</p>` : ""}
      ${client?.address ? `<p>${client.address}</p>` : ""}
    </div>
  </div>

  <div class="section">
    <h3>Items</h3>
    <table>
      <thead>
        <tr>
          <th>Description</th>
          <th class="right">Qty</th>
          <th class="right">Unit Price</th>
          <th class="right">Tax</th>
          <th class="right">Amount</th>
        </tr>
      </thead>
      <tbody>
        ${items.map((item: any) => `
          <tr>
            <td>${item.description}</td>
            <td class="right">${Number(item.quantity)}</td>
            <td class="right">${formatMoney(Number(item.unit_price))}</td>
            <td class="right">${Number(item.tax_rate)}%</td>
            <td class="right">${formatMoney(Number(item.amount))}</td>
          </tr>
        `).join("")}
      </tbody>
    </table>

    <div class="totals">
      <div class="totals-row">
        <span>Subtotal</span>
        <span>${formatMoney(Number(inv.subtotal))}</span>
      </div>
      <div class="totals-row">
        <span>Tax</span>
        <span>${formatMoney(Number(inv.tax_total))}</span>
      </div>
      <div class="totals-row">
        <span>Paid</span>
        <span>${formatMoney(Number(inv.amount_paid ?? 0))}</span>
      </div>
      <div class="totals-row total">
        <span>Balance</span>
        <span>${formatMoney(Number(inv.total) - Number(inv.amount_paid ?? 0))}</span>
      </div>
    </div>
  </div>

  ${inv.notes ? `
    <div class="notes">
      <h3>Notes</h3>
      <p>${inv.notes}</p>
    </div>
  ` : ""}

  <div class="footer">
    <p>Generated by Quoinv — quoinv.com</p>
  </div>
</body>
</html>
  `;
}

export function printPDF(html: string) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to print PDF");
    return;
  }
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
}