/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPlanRouteImport } from './routes/auth.plan'
import { Route as AuthPaymentRouteImport } from './routes/auth.payment'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppQuotationsRouteImport } from './routes/app.quotations'
import { Route as AppPaymentsRouteImport } from './routes/app.payments'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppClientsRouteImport } from './routes/app.clients'
import { Route as AppQuotationsNewRouteImport } from './routes/app.quotations.new'
import { Route as AppQuotationsIdRouteImport } from './routes/app.quotations.$id'
import { Route as AppInvoicesNewRouteImport } from './routes/app.invoices.new'
import { Route as AppInvoicesIdRouteImport } from './routes/app.invoices.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPlanRoute = AuthPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPaymentRoute = AuthPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsRoute = AppPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsNewRoute = AppQuotationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppQuotationsRoute,
} as any)
const AppQuotationsIdRoute = AppQuotationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppQuotationsRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesIdRoute = AppInvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppInvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/payment': typeof AuthPaymentRoute
  '/auth/plan': typeof AuthPlanRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/payment': typeof AuthPaymentRoute
  '/auth/plan': typeof AuthPlanRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/clients': typeof AppClientsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/invoices': typeof AppInvoicesRouteWithChildren
  '/app/payments': typeof AppPaymentsRoute
  '/app/quotations': typeof AppQuotationsRouteWithChildren
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/payment': typeof AuthPaymentRoute
  '/auth/plan': typeof AuthPlanRoute
  '/app/invoices/$id': typeof AppInvoicesIdRoute
  '/app/invoices/new': typeof AppInvoicesNewRoute
  '/app/quotations/$id': typeof AppQuotationsIdRoute
  '/app/quotations/new': typeof AppQuotationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/quotations'
    | '/app/reports'
    | '/app/settings'
    | '/auth/payment'
    | '/auth/plan'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/quotations/$id'
    | '/app/quotations/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/quotations'
    | '/app/reports'
    | '/app/settings'
    | '/auth/payment'
    | '/auth/plan'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/quotations/$id'
    | '/app/quotations/new'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/clients'
    | '/app/dashboard'
    | '/app/invoices'
    | '/app/payments'
    | '/app/quotations'
    | '/app/reports'
    | '/app/settings'
    | '/auth/payment'
    | '/auth/plan'
    | '/app/invoices/$id'
    | '/app/invoices/new'
    | '/app/quotations/$id'
    | '/app/quotations/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/plan': {
      id: '/auth/plan'
      path: '/plan'
      fullPath: '/auth/plan'
      preLoaderRoute: typeof AuthPlanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/payment': {
      id: '/auth/payment'
      path: '/payment'
      fullPath: '/auth/payment'
      preLoaderRoute: typeof AuthPaymentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations': {
      id: '/app/quotations'
      path: '/quotations'
      fullPath: '/app/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payments': {
      id: '/app/payments'
      path: '/payments'
      fullPath: '/app/payments'
      preLoaderRoute: typeof AppPaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clients': {
      id: '/app/clients'
      path: '/clients'
      fullPath: '/app/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/quotations/new': {
      id: '/app/quotations/new'
      path: '/new'
      fullPath: '/app/quotations/new'
      preLoaderRoute: typeof AppQuotationsNewRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
    '/app/quotations/$id': {
      id: '/app/quotations/$id'
      path: '/$id'
      fullPath: '/app/quotations/$id'
      preLoaderRoute: typeof AppQuotationsIdRouteImport
      parentRoute: typeof AppQuotationsRoute
    }
    '/app/invoices/new': {
      id: '/app/invoices/new'
      path: '/new'
      fullPath: '/app/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/app/invoices/$id': {
      id: '/app/invoices/$id'
      path: '/$id'
      fullPath: '/app/invoices/$id'
      preLoaderRoute: typeof AppInvoicesIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
  }
}

interface AppInvoicesRouteChildren {
  AppInvoicesIdRoute: typeof AppInvoicesIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesIdRoute: AppInvoicesIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppQuotationsRouteChildren {
  AppQuotationsIdRoute: typeof AppQuotationsIdRoute
  AppQuotationsNewRoute: typeof AppQuotationsNewRoute
}

const AppQuotationsRouteChildren: AppQuotationsRouteChildren = {
  AppQuotationsIdRoute: AppQuotationsIdRoute,
  AppQuotationsNewRoute: AppQuotationsNewRoute,
}

const AppQuotationsRouteWithChildren = AppQuotationsRoute._addFileChildren(
  AppQuotationsRouteChildren,
)

interface AppRouteChildren {
  AppClientsRoute: typeof AppClientsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppPaymentsRoute: typeof AppPaymentsRoute
  AppQuotationsRoute: typeof AppQuotationsRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppClientsRoute: AppClientsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppPaymentsRoute: AppPaymentsRoute,
  AppQuotationsRoute: AppQuotationsRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthPaymentRoute: typeof AuthPaymentRoute
  AuthPlanRoute: typeof AuthPlanRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthPaymentRoute: AuthPaymentRoute,
  AuthPlanRoute: AuthPlanRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
